function regr_earn_age_year_show(regrV, profS, saveFigures, setNo)
% Show results of wage regressions
%{
Log earnings (not wages) on age and time dummies

IN
   regrV{iSchool}
      regression results generated by regr_earn_age_year
   profS
      settings for profiles (from settings.m)
   figPrefix
      for figure file names (dir and start of file name)
%}

cS = const_cpsearn(setNo);
figS = const_fig_cpsearn;
figPrefix = profS.prefixStr;


%% Age dummies
if 1
   % Normalize dummies to 0 for this age
   refAge = 25;
   fh = output_cpsearn.fig_new(saveFigures, []);
   hold on;
   for iSchool = 1 : cS.nSchool
      regrS = regrV{iSchool};
      refAgeIdx = find(regrS.ageValueV == refAge);
      plot(regrS.ageValueV, regrS.ageDummyV - regrS.ageDummyV(refAgeIdx), ...
         figS.lineStyleDenseV{iSchool}, 'color', figS.colorM(iSchool,:));
   end
   hold off;
   xlabel('Age');
   ylabel('Age dummy');
   legend(cS.sLabelV, 'Location', 'south');
   output_cpsearn.fig_format(fh, 'line');
   output_cpsearn.save_fig([figPrefix, 'age_dummies'], saveFigures, [], setNo);
end


%% Year dummies
if 1
   % Normalize dummies to 0 for this year
   refYear = 1970;
   fh = output_cpsearn.fig_new(saveFigures, []);
   hold on;
   for iSchool = 1 : cS.nSchool
      regrS = regrV{iSchool};
      refYearIndex = find(regrS.yearValueV == refYear);
      plot(regrS.yearValueV, regrS.yearDummyV - regrS.yearDummyV(refYearIndex), ...
         figS.lineStyleDenseV{iSchool}, 'color', figS.colorM(iSchool,:));
   end
   hold off;
   xlabel('Age');
   ylabel('Year dummy');
   legend(cS.sLabelV, 'Location', 'south');
   output_cpsearn.fig_format(fh, 'line');
   output_cpsearn.save_fig([figPrefix, 'year_dummies'], saveFigures, [], setNo);
end


end